### ISSUE TITLE
FAILED

### ISSUE THREAD

**Issue by DesKaOne** [NodleCode/nodlesdk-quickstart-android#5]
[NODLE] SDK INIT: FAILED

**Comment by Suigenerisbrasil** [comment]
What problem would number 5 be?
Send By•小米Mi11 Ultra•Ellen Sousa

**Comment by higoramp** [comment]
Same issue here

`System.out              com...k.android.nodlesdk.quickstart  I  [NODLE] SDK INIT: FAILED`
